name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/app/devx/contracts/utility-contracts/fee-deduction

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev pkg-config

      - name: Install Scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.9.1

      - name: Add Scarb to PATH
        run: echo "${HOME}/.local/share/scarb/bin" >> $GITHUB_PATH

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            client/app/devx/contracts/utility-contracts/fee-deduction/target/
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache forge
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-forge-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Universal Sierra Compiler
        run: curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh

      - name: Install Starknet Foundry (snforge)
        run: |
          if ! command -v snforge &> /dev/null; then
            git clone https://github.com/foundry-rs/starknet-foundry.git
            cd starknet-foundry
            git checkout v0.44.0
            cargo build --release
            sudo cp target/release/snforge /usr/local/bin/snforge
            cd ..
            rm -rf starknet-foundry
          fi
          snforge --version

      - name: Install dependencies
        run: |
          scarb clean
          scarb fetch

      - name: Build Starknet contracts
        run: scarb build

      - name: Run forge tests
        run: snforge test --workspace

  nextjs-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./client/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ github.event_name == 'pull_request' && 'dummy-api-url' || secrets.NEXT_PUBLIC_API_URL }}
          OPENAI_API_KEY: ${{ github.event_name == 'pull_request' && 'dummy-key' || secrets.OPENAI_API_KEY }}
          BRIAN_API_KEY: ${{ github.event_name == 'pull_request' && 'dummy-key' || secrets.BRIAN_API_KEY }}

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            ./client/.next/cache
            ./client/.next/static
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-${{ hashFiles('client/**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-

  docker-build-and-push:
    needs: [check-contracts, nextjs-build-and-test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for GitHub Container Registry

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/starkfinder-backend:latest

      - name: Build and Push ElizaOS Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.agent
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/starkfinder-agent:latest

  deploy:
    needs: [check-contracts, nextjs-build-and-test, docker-build-and-push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./client/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BRIAN_API_KEY: ${{ secrets.BRIAN_API_KEY }}
