name: Deploy Preview to Vercel

on:
  pull_request:
    branches:
      - main

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Debug VERCEL_TOKEN
        run: "echo \"VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}\""

      - name: Pull Environment Variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        run: |
          DEPLOY_URL=$(vercel --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "DEPLOYMENT_URL=$DEPLOY_URL" >> $GITHUB_ENV

      - name: Comment Preview URL on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: "🚀 Preview deployed: [View Deployment](${{ env.DEPLOYMENT_URL }})"
          repo-token: ${{ secrets.GITHUB_TOKEN }}