name: Deploy Preview to Vercel

on:
  pull_request:
    branches:
      - main

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Environment Variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --scope your-vercel-team-name

      - name: Get Deployment URL
        run: echo "DEPLOYMENT_URL=$(vercel --token=${{ secrets.VERCEL_TOKEN }} --scope your-vercel-team-name)" >> $GITHUB_ENV

      - name: Comment Preview URL on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: "🚀 Preview deployed: [View Deployment](${{ env.DEPLOYMENT_URL }})"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
